schema: "classroom50/repo-config/v1"
classroom: "mm2026s2"
assignment: "getting-started-with-asm"
owner:
  username: "menotti"
  id: 1031350
  accepted_at: "2026-08-18T15:41:35Z"
source:
  owner: "DC-UFSCar"
  owner_id: 11891488
  repo: "getting-started-asm"
  branch: "main"
